blank_issues_enabled: false
contact_links:
  - name: Stackbird.new related issues
    url: https://github.com/stackblitz/stackbird.new/issues/new/choose
    about: Report issues related to Stackbird.new (not Stackbird.diy)
  - name: Chat
    url: https://thinktank.ottomator.ai
    about: Ask questions and discuss with other Stackbird.diy users.
